### ISSUE TITLE
Broken CI status

### ISSUE THREAD

**Issue by s-celles** [adafruit/Adafruit_LvGL_Glue#6]
Hello,

I noticed that CI status of this library is currently broken.
Any chance to have this fixed?
https://github.com/adafruit/Adafruit_LvGL_Glue/actions
https://github.com/adafruit/Adafruit_LvGL_Glue/actions/runs/257944479 latest build

Kind regards

**Comment by ladyada** [comment]
its probably due to lvgl library's latest version being incompatible.

**Comment by s-celles** [comment]
`arduino-cli` provides a way to install a specific version number of an Arduino library.
See https://github.com/arduino/arduino-cli/issues/105#issuecomment-783297585 (unfortunately version restriction doesn't seems to be currently supported).

Maybe you can set CI to use the lvgl library version number that was working previously.

I also noticed in
https://github.com/adafruit/Adafruit_LvGL_Glue/blob/4667e886791f980a5db6dc8d3dab6152f19080b5/library.properties#L10

    depends=...lv_arduino

but according https://github.com/lvgl/lv_arduino/issues/63 lv_arduino is now archived.

**Comment by ladyada** [comment]
yeah it needs a update to https://github.com/lvgl/lvgl
would you like to take a crack at it & submit a PR?

**Comment by s-celles** [comment]
Sorry @ladyada I'm not sure to have nor the background nor the available time in the next coming weeks for this kind of stuff.

**Comment by ladyada** [comment]
we dont either :D
